# Generated by Django 5.2.15 on 2026-06-16 08:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CropProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "crop_type",
                    models.CharField(
                        choices=[
                            ("pot", "Pot (greenhouse, per-pot)"),
                            ("crop", "Field crop (outdoor, drone) — coming soon"),
                            ("other", "Other"),
                        ],
                        default="pot",
                        max_length=8,
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        blank=True,
                        help_text="Lowercase common name (strawberry, watermelon, tomato). Drives LAD lookup.",
                        max_length=60,
                    ),
                ),
                ("planted_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "cover_thumb",
                    models.ImageField(blank=True, null=True, upload_to="thumbs/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-created_at"],
                        name="projects_cr_owner_i_575765_idx",
                    ),
                    models.Index(
                        fields=["owner", "crop_type"],
                        name="projects_cr_owner_i_7e9088_idx",
                    ),
                ],
            },
        ),
    ]
