# Generated by Django 5.2.15 on 2026-06-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="cropproject",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Shared labels grouping projects (many-to-many).",
                related_name="projects",
                to="projects.tag",
            ),
        ),
    ]
