# Generated by Django 5.2.15 on 2026-06-16 08:54

import apps.measurements.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.measurements.models.upload_video_path,
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the video was recorded (user-editable; defaults to upload time).",
                    ),
                ),
                ("fps_target", models.PositiveSmallIntegerField(default=10)),
                (
                    "scale_ref_m",
                    models.FloatField(
                        blank=True,
                        help_text="Known reference length (e.g., pot diameter) for volume_lai scale anchor.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("queued", "Queued"),
                            ("extracting", "Extracting frames"),
                            ("reconstruct", "Reconstructing"),
                            ("analyzing", "Analyzing LAI"),
                            ("rendering", "Rendering preview"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="uploading",
                        max_length=16,
                    ),
                ),
                ("status_msg", models.CharField(blank=True, max_length=255)),
                ("progress_pct", models.PositiveSmallIntegerField(default=0)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "pinned",
                    models.BooleanField(
                        default=False, help_text="If True, NPZ is not auto-deleted."
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_trace", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="projects.cropproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-captured_at"],
                        name="measurement_project_b4b6e9_idx",
                    ),
                    models.Index(
                        fields=["status"], name="measurement_status_dac04b_idx"
                    ),
                ],
            },
        ),
    ]
