# Generated by Django 5.2.15 on 2026-06-16 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendSnapshot",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="trend",
                        serialize=False,
                        to="projects.cropproject",
                    ),
                ),
                ("metric", models.CharField(default="agg_column_lai", max_length=24)),
                ("poly_degree", models.PositiveSmallIntegerField(default=1)),
                (
                    "coeffs",
                    models.JSONField(
                        help_text="numpy.polyfit output, highest power first."
                    ),
                ),
                ("r_squared", models.FloatField()),
                ("horizon_days", models.PositiveSmallIntegerField(default=14)),
                ("forecast", models.JSONField(help_text="[{day_offset, value}, ...]")),
                ("n_points", models.PositiveSmallIntegerField()),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
